### ISSUE TITLE
对node版本有特别要求吗

### ISSUE THREAD

**Issue by yuanshanxiaoni** [p455555555/nest-oss#2]
抛出如下错误：

`00:26:39 - Found 0 errors. Watching for file changes.
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/darius/workspace/2020/la-server/node_modules/@nest-public/nest-oss/lib/src/oss.works.js:3:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
`

我的环境：
node版本： 10.14
npm: 6.12.1
nest：6.10.14

代码：

OSSModule.forRoot({
      client: {
        endpoint: 'oss-cn-shenzhen.aliyuncs.com', // endpoint域名
        accessKeyId: '*', // 账号
        accessKeySecret: '', // 密码
        bucket: 'test-bucket', // 存储桶
        internal: false, // 是否使用阿里云内部网访问
        secure: false, // 使用 HTTPS
        cname: false, // 自定义endpoint
      }
    })

谢谢

**Comment by yuanshanxiaoni** [comment]
是node的版本的原因，11以上就可以了
